### ISSUE TITLE
On Linux, the developer console is shown

### ISSUE THREAD

**Issue by probonopd** [l3laze/ReliefValve#1]
When launching the ReliefValve AppImage, this is what I get:

![screenshot from 2017-02-23 18-43-26](https://cloud.githubusercontent.com/assets/2480569/23271532/0d292f6a-f9f8-11e6-86a4-844d24fd21ca.png)

**Comment by l3laze** [comment]
That's actually on all systems. I got so used to testing with devtools open so I can see the console easily that I completely forgot to remove it; I'm sorry. I will add this to the list of things to do before the next release, which I'm going to try to do tonight. Thank you for this - my first GitHub Issue :) Kinda feel like a real programmer.

**Comment by l3laze** [comment]
Fixed in commit #https://github.com/l3laze/ReliefValve/commit/66539978b6cc3c2427ccf925b2a3bc45a4476340. Thank you for the help :)

**Comment by probonopd** [comment]
Thanks for fixing this and congrats on successfully closing your first GitHub Issue :+1:

**Comment by l3laze** [comment]
Very welcome, and thank you 😃
