### ISSUE TITLE
[Linux] desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [l3laze/ReliefValve#8]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by l3laze** [comment]
Thank you, yet again! :) Now my second GitHub Issue. Lol.


I've been working on a bunch of other projects, but have been thinking about this one a lot lately. I have learned a couple things that would help a little in this project too; I will get to work on updating, but it will likely take at least a few days until I can finish it properly.

**Comment by l3laze** [comment]
Fixed with ReliefValve [v1.2.2](https://github.com/l3laze/ReliefValve/releases/tag/v1.2.2) at #9.

Thank you, again :)

Edit: changed v1.2.2 to a link to v1.2.2 in Releases.

**Comment by probonopd** [comment]
Thanks, added to https://github.com/AppImage/appimage.github.io/commit/f16e93f644d97428b67111de903020bd6d2fd26d

**Comment by l3laze** [comment]
Very welcome, and thank you 👍
